### ISSUE TITLE
Material surface is not applied

### ISSUE THREAD

**Issue by pixelartchemist** [mrven/Blender-Asset-Creation-Toolset#10]
Before export:
![image](https://user-images.githubusercontent.com/60591594/184526508-bbc97ece-ad4f-44a3-9f85-a0e0f9a362b6.png)

Reimporting it back to blender, we see:
![image](https://user-images.githubusercontent.com/60591594/184526562-4c9ffb6d-9832-4766-b46c-44a4d69b9086.png)

Emission became principled BSDF

Blender 3.2.2

**Comment by mrven** [comment]
It's Blender FBX Exporter Limitations. You can try it with default File -> Export -> FBX.
1. Create Object with Emission Material.
![Image1](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/826db684-bbbe-4c75-9a42-239634002e8a)

2. Export model with File -> Export -> FBX.
3. Import model to Blender with File -> Import -> FBX. Material will be Principled BSDF
![Image2](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/b15e969f-e219-4c33-9330-645024aaabf9)
