### ISSUE TITLE
Exporting FBX's doesn't work if the mesh contains characters which windows doesn't allow (For example " : ")

### ISSUE THREAD

**Issue by nicknemer** [mrven/Blender-Asset-Creation-Toolset#12]
Hi Ivan, I've had following problem:
I had a mesh with the name "Studio:Assets_01". When exporting the FBX, it would just write a file with the name "Studio" , all the characters until the forbidden character, no mesh Information or extension. 

Possible solution: check for forbidden characters on export and replace them with "_" or show a warning or at least let people know some characters cause problems. I didn't know why exporting some meshes worked and others didn't (my file naming wasn't consistent).

Thank you for your incredible plugin, it has helped me a lot :)

**Comment by mrven** [comment]
Thanks for report. I Add prefilter for some characters: Will be notice about wrong chars and replace with "_"

**Comment by mrven** [comment]
Feature added in future version
