### ISSUE TITLE
Merge Bones :( 

### ISSUE THREAD

**Issue by NefistoSamael** [mrven/Blender-Asset-Creation-Toolset#13]
File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Asset_Creation_Toolset_3_3_341\other_tools.py", line 140, in execute

	parent_mesh.modifiers['VertexWeightMix'].vertex_group_a = active_bone_name

KeyError: 'bpy_prop_collection[key]: key "VertexWeightMix" not found

**Comment by mrven** [comment]
Can't reproduce. Could you send me example or steps for reproduce?

**Comment by mrven** [comment]
Added more checks and support of multi mesh rig in future version
