### ISSUE TITLE
Linked Objects are not output as the same mesh data

### ISSUE THREAD

**Issue by DONAMO-163** [mrven/Blender-Asset-Creation-Toolset#14]
Blender version ...3.5.1
ACT version ...3.3.341
Unity version ...2019.4.31f1

If export FBX from the Import/Export tab as "All->One FBX" and import it into Unity, the mesh data created by the link duplication will be imported as different mesh data.

Reproduction is very easy.
1. create a new .blend file and mesh, link duplicate it.
2. select the source and destination mesh data, and export FBX with the options "All->One FBX" and "Apply Rotate and Scale" from the Import/Export tab.
3. Import the FBX into Unity by D&D.
4. In the case of Cube, the mesh data is divided into "Cube" and "Cube.001".

**Comment by mrven** [comment]
Thanks for report. In Progress

**Comment by mrven** [comment]
Fixed in future version
