### ISSUE TITLE
Scale when exporting to Unity is incorrect by 100.

### ISSUE THREAD

**Issue by BEDDALL** [mrven/Blender-Asset-Creation-Toolset#23]
This previously worked fine in version 3_3_341. But now exporting to Unity and the mesh comes in 100x too small. Apply scale is checked. units are in metric. import scale in unity is set to 1. yet a 32m cube from Blender appears as a 32cm cube in Unity.

**Comment by mrven** [comment]
Read Description about new export algorithm on main page, please. You also can use old export algorithm if you select Unity (Legacy) Engine Target. 
![изображение](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/63caee15-7b9a-4564-ae62-5fffa38d998e)
![изображение](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/fe91c82f-d334-4926-bd3d-49e113f3d794)
![изображение](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/b265b380-5692-4d52-8134-78efd61d1643)

**Comment by BEDDALL** [comment]
Ok. Seems it isn't a bug. Tho I would perhaps suggest having a link to the documentation in the addon itself. If you get the addon from Gumroad or similar then there is no need to ever visit github. The only link in the addon is to report a bug which bought me here. A documentation link to the main page would be super useful. thanks
