### ISSUE TITLE
Option to disable x-rotation fix when exporting OBJ

### ISSUE THREAD

**Issue by PanicPug** [mrven/Blender-Asset-Creation-Toolset#26]
Would it be possible to add an option to disable the x-rotation "fix" when exporting OBJs? 
When exporting FBX there are a few options, but none when exporting OBJ:

FBX
![image](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/11910245/a8aeda22-a45e-4fed-8bd4-48ea7cba8d5e) ![image](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/11910245/52b42b6d-4d18-404c-8121-997b359bdfd6)

OBJ
![image](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/11910245/70ff533b-d29d-4802-85d0-5ad035f26732)

**Comment by mrven** [comment]
Ouch. It's missing for OBJ. I will check and fix that. Thank you for report!

**Comment by mrven** [comment]
Fixed in aaa9deb6d6c8752f9536220b2fbe640d40010a50
