### ISSUE TITLE
Unity Error CS0518, CS 0656

### ISSUE THREAD

**Issue by michelepoletto3d** [mrven/Blender-Asset-Creation-Toolset#27]
Hi, 
when I try to install the Unity Package, Unity give me this error:
![image](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/140184744/a604fdc2-7fd2-4dec-9841-69321b9b69bb)

I have a project with this Unity version 2020.2.5f1.4029 

How can I resolve this issue?

**Comment by mrven** [comment]
Hi! Unity 2020 is too old version for supporting. You can use "Unity (Legacy)" export profile. It doesn't need any additional steps in Unity
