### ISSUE TITLE
ACT with blender 4,0,1 export to unity 

### ISSUE THREAD

**Issue by RobAllsopp-hub** [mrven/Blender-Asset-Creation-Toolset#29]
Im having issues were the Unity Export scale is not working as it used to all objects scale is 0,01. i was wondering when an update for blender 4.0.1

**Comment by mrven** [comment]
Hi! From latest ACT has two different Unity export profiles.
Please Check Documentation https://github.com/mrven/Blender-Asset-Creation-Toolset about new and old export algorithms.
![изображение](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/9b7bde67-1667-469a-93bf-e661e13a7ce3)
![изображение](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/b2e19531-e853-413a-a924-2474a80142f3)
