### ISSUE TITLE
Model to look backwards.

### ISSUE THREAD

**Issue by ani-kun** [mrven/Blender-Asset-Creation-Toolset#30]
"Bake Axis Conversion" enabled causes the FBX model to look backwards in Unity.
If "Bake Axis Conversion" is to be used, wouldn't it be better export to set "use_space_transform" to "False" and -Y axis set forward?

**Comment by ani-kun** [comment]
Would the appearance on the 2D View be a basis? Surely TextMesh, for example, is facing forward by default, but isn't that because of the UI?

Also, the teddy bear in the official documentation looks like a Z Forward model.
https://docs.unity3d.com/ja/2023.2/Manual/GameObjects.html

Furthermore, if we are talking about compatibility, we are losing orientation compatibility (commonality) with existing fbx. If you want to overwrite old fbx with models exported with the new options, you will need to rotate the prefab as to not only change the FBX import options.

Sorry for those who are already using models exported with the "Unity2023" option, but the sooner you make the change, the better.

**Comment by mrven** [comment]
Ok. I will fix that and temporary add option for compatibility. And finally will remove "Unity (Legacy)" option

**Comment by ani-kun** [comment]
Thanks.

However, I don't see the need to remove "Unity (Legacy)" option in the future.

There may be a reason why you want to keep the Scale Factor at 1.
For example, a model that has already been animated would have to be reanimated if the new Unity option was used to overwrite it.

Why would we need to remove it?

**Comment by mrven** [comment]
I want to remove this option due to the increasing complexity of the code. I think I’ll then move this code into a separate function, which I won’t change anymore

Thank you for your feedback! 👍

**Comment by mrven** [comment]
Fixed in 2024.2
