### ISSUE TITLE
Support for Blender Custom Properties via AssetPostprocessor

### ISSUE THREAD

**Issue by Anto775** [mrven/Blender-Asset-Creation-Toolset#31]
Blender can store many variables into an FBX via it's Custom Properties, theses can be later picked up in-engine after being imported with the AssetPostprocessor. This feature would greatly streamline the iteration and overall workflow between Blender & Unity. 

Here's a practical article of a team that used this approach;
[https://blog.unity.com/games/rapid-design-iteration-in-breachers-using-assetpostprocessor-and-blender](url)

**Comment by mrven** [comment]
Added in v2024.1
