### ISSUE TITLE
FBX exports's size incorrect

### ISSUE THREAD

**Issue by zbartan** [mrven/Blender-Asset-Creation-Toolset#36]
Fbx Unity exports export as 1/100 size. for instance a 1m x 1m x 1m object exported as 1cm x 1cm x 1cm. Blender default exports works as intended but export with add-on has the issue at same blender client/file. Problem only exist in FBX export, obj and gltf export works correct.

![resim](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/85178459/b29c7b39-ceab-469e-bb04-27fa80ac1fad)
![resim](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/85178459/1ff0e3ad-0f20-45ff-b3f9-25da8dc0e433)

**Comment by zbartan** [comment]
Unity (Legacy) works as intended

**Comment by mrven** [comment]
It's correct. You can read about this in a documentation https://github.com/mrven/Blender-Asset-Creation-Toolset?tab=readme-ov-file#export-algorithm-for-unity
