### ISSUE TITLE
Create Palette Texture Add metallicity and roughness

### ISSUE THREAD

**Issue by 1405100494** [mrven/Blender-Asset-Creation-Toolset#37]
Hi!
I want to save performance and export externally for my solid color device, can I add metallicity and coarse degree options? It's not just for low poly. Any solid color model will work for these textures, and my realistic mechanical equipment is almost always solid color.
Thanks!

**Comment by mrven** [comment]
You can check "PBR Workflow" for that. In This case will be baked Diffuse, Roughness, Metallic, Emission and Opacity.
![image](https://github.com/user-attachments/assets/5e6c2f71-d43c-4779-8ee4-e4642479a69f)
