### ISSUE TITLE
Object with wrong rotations when exporting to Unity on version 2024.3.3

### ISSUE THREAD

**Issue by EvandroFCosta** [mrven/Blender-Asset-Creation-Toolset#41]
**Worked as expected**: External addon Asset_Creation_Toolset_3_3_341.zip
**Not Working as expected**: Extension inside blender version 2024.3.3
Blender version: 4.2.2

Having an object with all rotations 0,0,0 and exporting to Unity with any of these three options: One-on-one, All-on-One, By Parent, makes the object imported in unity come with a -90, 0, 180 degrees rotation on X/Y/Z. The only option that doesn't export with rotations is By Collection, but this one comes out with wrong scale/pivot.
The options to apply Location/Rotation/Scale are active during the export.

This did not happen on the addon version 3_3_341 which exported the objects correctly, without any rotation, with correct scale in every export and on locations matching the pivot, (except the By Collection had the pivot not matching the model, but instead on world 0,0,0).

This happens with a single object export or even when exporting multiple objects as LODs.

**Comment by mrven** [comment]
Please, follow documentation https://github.com/mrven/Blender-Asset-Creation-Toolset?tab=readme-ov-file#export-tools
From version 2023 ACT has two different ways for Unity
![image](https://github.com/user-attachments/assets/675e7b99-8582-42aa-8e93-b5801471d4ef)
