### ISSUE TITLE
(Origin Tools) add Origin Align Middle

### ISSUE THREAD

**Issue by mokalux** [mrven/Blender-Asset-Creation-Toolset#6]
Thank you for sharing this awesome blender plugin ;-)

I have a request please: would it be possible to add in the **Origin Tools** an **Origin Align Middle** like we have **Min** and **Max**?

I think this could be useful if we want to put the origin in the center of the object on the X, Y and Z coordinates.

Thank you!

**Comment by mokalux** [comment]
see pull request https://github.com/mrven/Blender-Asset-Creation-Toolset/pull/7/commits/4b9b4e5af6ab2c73855f32884a2dbf769eeb24f0

**Comment by mrven** [comment]
Thank you for request! I will review it soon. Sorry for long reply

**Comment by mrven** [comment]
Added to future version
