### ISSUE TITLE
Exporting cuts out part of the asset name if it's long, but it's not a constant character limit

### ISSUE THREAD

**Issue by PabloCaracena** [mrven/Blender-Asset-Creation-Toolset#9]
Windows 10
Blender 3.2.1
Asset Creation Toolset 3.2 (latest as today)

---------------------------------------------------------------------

Thanks for the addon! I use it a lot in my job.

I have these 2 objects in Blender: 

-UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a_01
-UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a_02

When I export them, using the "By Parent" option, both parented to the main object(S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a), the names (in Blender and in the export FBX) turn into:

-UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a
-UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a_

Which are different name lengths, it seems to me like some bug, not a character limit. It happened to me too with the 1 Obj->1 FBX, but I thought it was just a character limit for some reason.

**Comment by mrven** [comment]
It isn't a ACT Bug. It's Blender Limitations.
1. Create object with name "UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a_01"
2. Duplicate this with Shift+D
3. New Object has name "UCX_S_AG_VIL_HouseStoneWall_Corner_Broken_300x300_Solid_01a"

![Image](https://github.com/mrven/Blender-Asset-Creation-Toolset/assets/6444269/7c178e90-98bc-4421-9da0-796dc5528a6e)
